### ISSUE TITLE
Blank screen after character dies

### ISSUE THREAD

**Issue by mfreed** [mdwelsh/infinitube#1]
Fairly regularly, after I die and the game restarts, the content doesn't seem to scroll up.  The character appears in the middle of the screen and can jet back and forth, but nothing else happens.  Screen shot attached.

Chrome on MacOS.

![image](https://user-images.githubusercontent.com/205086/28446847-74709e9e-6d9b-11e7-8d5b-bf56e1c3cdc5.png)

**Comment by mdwelsh** [comment]
Hmmm. I think I must have a bug with resetting the game state after a restart. I'll take a look.

**Comment by mdwelsh** [comment]
Mike -- Can you do the following the next time this happens?
- Pause the game (hit spacebar)
- Open JS console
- Type dump() 
- Post the output here?

**Comment by mfreed** [comment]
{  
   "device":{  
      "deviceReadyAt":1500612682165,
      "initialized":true,
      "desktop":true,
      "iOS":false,
      "iOSVersion":0,
      "cocoonJS":false,
      "cocoonJSApp":false,
      "cordova":false,
      "node":false,
      "nodeWebkit":false,
      "electron":false,
      "ejecta":false,
      "crosswalk":false,
      "android":false,
      "chromeOS":false,
      "linux":false,
      "macOS":true,
      "windows":false,
      "windowsPhone":false,
      "canvas":true,
      "canvasBitBltShift":true,
      "canHandleAlpha":true,
      "canUseMultiply":true,
      "webGL":true,
      "file":true,
      "fileSystem":false,
      "localStorage":true,
      "worker":true,
      "css3D":true,
      "pointerLock":true,
      "typedArray":true,
      "vibration":true,
      "getUserMedia":true,
      "quirksMode":false,
      "touch":false,
      "mspointer":true,
      "wheelEvent":"wheel",
      "arora":false,
      "chrome":true,
      "chromeVersion":59,
      "epiphany":false,
      "firefox":false,
      "firefoxVersion":0,
      "ie":false,
      "ieVersion":0,
      "trident":false,
      "tridentVersion":0,
      "edge":false,
      "mobileSafari":false,
      "midori":false,
      "opera":false,
      "safari":false,
      "safariVersion":0,
      "webApp":false,
      "silk":false,
      "audioData":true,
      "webAudio":true,
      "ogg":true,
      "opus":true,
      "mp3":true,
      "wav":true,
      "m4a":true,
      "webm":true,
      "dolby":false,
      "oggVideo":true,
      "h264Video":true,
      "mp4Video":true,
      "webmVideo":true,
      "vp9Video":true,
      "hlsVideo":false,
      "iPhone":false,
      "iPhone4":false,
      "iPad":false,
      "pixelRatio":2,
      "littleEndian":true,
      "LITTLE_ENDIAN":true,
      "support32bit":true,
      "fullscreen":true,
      "requestFullscreen":"webkitRequestFullscreen",
      "cancelFullscreen":"webkitCancelFullScreen",
      "fullscreenKeyboard":false,
      "onInitialized":null,
      "_readyCheck":null,
      "_initialize":null
   },
   "innerWidth":858,
   "innerHeight":712,
   "devicePixelRatio":2,
   "tileSize":30,
   "screenWidth":40,
   "screenHeight":23,
   "worldWidth":40,
   "worldHeight":46,
   "numLives":2,
   "invincible":true,
   "playerDead":false,
   "curLayer":272,
   "lastPopulatedLayer":null,
   "numGearsCollected":0,
   "lastCheckpointCreated":-3,
   "lastCheckpointTraversed":200,
   "checkpointsTraversed":1,
   "lastTick":"2017-07-21T04:51:54.898Z",
   "jetpackFuel":100,
   "lastJetpackUse":0,
   "numParachutes":4,
   "parachuteInUse":false,
   "rightSizing":false,
   "lowestMarker":1350,
   "platforms":[  

   ],
   "spikes":[  

   ],
   "floatySpikes":[  

   ],
   "worms":[  

   ],
   "items":[  

   ],
   "fans":[  

   ]
}

**Comment by mdwelsh** [comment]
Very strange. A few of those variables should not have those values. I'll
need to dig a bit to understand why. Is this happening after you die once,
or is it happening after you restart the game after dying 3 times?

**Comment by mdwelsh** [comment]
Can you try the most recent version (hard reload to avoid cache)?

**Comment by mfreed** [comment]
Seems happier now.  👍
